### ISSUE TITLE
PM09 Issues

### ISSUE THREAD

**Issue by jjgiesey** [Milligan-Engineering/AutoFile#1]
1. Going to need pre and post conditions for Case2 (420
2. Would tagInputNumber<1 || tagInputNumber >10 work? (233)
3. Eventually you will want to make a way to remove tags in case of a mistake.
4. Option 3 was not closing.
5. Read and write tags from/to file.

**Comment by TimThacker** [comment]
Each of these have been resolved. I know John found several other bugs, however currently:
1. Case2 has pre and post conditions.
2. tagInputNumber<1 || tagInputNumber >10 did work on like 223 and has been implemented.
3. The closing option has been moved to choice 4, while choice 3 is now available for such a feature.
4. Option 4 now closes the program properly.
5. File I/O should be working properly now.

**Comment by jjgiesey** [comment]
Issues resolved in PM10.
